table 'Analysis DAX'
	lineageTag: 445c1cb0-47b0-4e8b-986b-300a640b0447

	measure 'Net Sales' =
			
			CALCULATE ( SUM ( Sales[Amount] ), Sales[Status] = "Sold" )
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: cd2e7756-eb39-41a6-a73c-36aecb7b43c8

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Net Sales PM' =
			
			CALCULATE ( [Net Sales], PREVIOUSMONTH ( 'Calendar'[Date] ) )
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: b71875ff-9152-49a3-9651-654f7beb05e9

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Last 2 Months Net Sales' =
			
			[Net Sales] + [Net Sales PM]
		formatString: 0
		lineageTag: 476b56d5-ccb7-4f18-a60a-d1ed841caaf7

	measure 'Net Sales Variance' =
			
			[Net Sales] - [Net Sales PM]
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: ea94c27a-07f9-4dcb-9c51-33ecf46a07b2

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Net Sales Variance %' =
			
			DIVIDE ( [Net Sales], [Net Sales PM], 0 ) - 1
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2263b9a4-5117-4e64-a425-7236388fc050

	measure 'Units Sold' =
			
			CALCULATE ( SUM ( Sales[Unit] ), Sales[Status] = "Sold" )
		formatString: #,0
		lineageTag: 4f6b44ec-7552-484e-bd67-124e67a7c385

	measure 'Units Sold PM' =
			
			CALCULATE ( [Units Sold], PREVIOUSMONTH ( 'Calendar'[Date] ) )
		formatString: #,0
		lineageTag: d51c6348-be52-401c-a2c7-677e67d72580

	measure 'Units Sold Variance %' =
			
			DIVIDE ( [Units Sold], [Units Sold PM], 0 ) - 1
		lineageTag: 7ce11e74-aa12-487e-a6af-cbbd11542942

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Returns =
			
			CALCULATE ( SUM ( Sales[Amount] ), Sales[Status] = "Returned" )
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: 09023869-ae68-4a3a-9d35-a6becc131965

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Returns PM' =
			
			CALCULATE ( [Returns], PREVIOUSMONTH ( 'Calendar'[Date] ) )
		formatString: #,0
		lineageTag: eccc0c03-68f2-488a-9858-acaa5ec1d949

	measure 'Last 2 Months Returns' =
			
			[Returns] + [Returns PM]
		formatString: 0
		lineageTag: 81e36c3f-3f30-4970-ac53-6009af8b216b

	measure 'Returns Variance' =
			
			[Returns] - [Returns PM]
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 5751baf5-17f8-4fae-849d-1f17457f0d15

	measure 'Returns Variance %' =
			
			( DIVIDE ( [Returns], [Returns PM], 0 ) - 1 )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 936690a6-4116-4d5b-93b7-6c64656a625a

	measure 'Units Returned' =
			
			CALCULATE ( SUM ( Sales[Unit] ), Sales[Status] = "Returned" )
		formatString: #,0
		lineageTag: 56a36fdf-16d1-46a9-b22d-63f6f074374d

	measure 'Units Returned PM' =
			
			CALCULATE ( [Units Returned], PREVIOUSMONTH ( 'Calendar'[Date] ) )
		formatString: 0
		lineageTag: 6b4eb375-20c9-4c6b-ab5a-d750c863bfb8

	measure 'Units Returned Variance %' =
			
			DIVIDE ( [Units Returned], [Units Returned PM], 0 ) - 1
		lineageTag: c0856a37-73e9-41a6-99f1-297c427cb949

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Return Rate' =
			
			DIVIDE (
			    ( ROUND ( ( ( DIVIDE ( [Returns], SUM ( Sales[Amount] ), 0 ) ) * 100 ), 0 ) ),
			    100,
			    0
			)
		formatString: 0%;-0%;0%
		lineageTag: c3645989-c086-47ba-af31-e12ac4d4d52c

	measure 'WIF Units Returned' =
			
			IF (
			    [Units Returned] - [WIF Units Returned Average] < 0,
			    0,
			    [Units Returned] - [WIF Units Returned Average]
			)
		lineageTag: 66092a0d-befe-4048-8c0f-9828990a5333

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WIF Units Returned Average' =
			
			DIVIDE (
			    [WIF Units Returned Difference],
			    CALCULATE ( DISTINCTCOUNT ( 'Calendar'[Date] ), ALL ( 'Calendar' ) ),
			    0
			)
		lineageTag: 9d462e15-7dd7-4344-bca7-a938a314eb8b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WIF Units Returned Difference' =
			
			[WIF Units Returned_1] - [WIF Units Returned_2]
		lineageTag: 95f5e193-f587-47d6-aa98-be16ec2cf701

	measure 'WIF Units Returned_1' =
			
			CALCULATE ( [Units Returned], ALLSELECTED ( 'Calendar'[Date] ) )
		formatString: 0
		lineageTag: 978a4e31-2673-45a2-be8b-86bdd31dfd8d

	measure 'WIF Units Returned_2' =
			
			CALCULATE ( [WIF Adjusted Units Returned], ALLSELECTED ( 'Calendar'[Date] ) )
		lineageTag: b365a446-2b19-472e-bab1-6dd79ad89b11

	measure 'WIF Adjusted Units Returned' =
			
			DIVIDE ( ( SUM ( Sales[Unit] ) * '% Return Rate'[% Return Rate Value] ), 1, 0 )
		lineageTag: 4da2584d-d264-4f58-afb1-d6c7d29b9324

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WIF Adjusted Net Sales' =
			
			( SUM ( Sales[Unit] ) * [WIF Price per Unit] )
			    - DIVIDE ( ( SUM ( Sales[Unit] ) * '% Return Rate'[% Return Rate Value] ), 1, 0 ) * [WIF Price per Unit]
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: 89f3d61f-24b1-4b8a-a8b8-846c36501d89

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'WIF Price per Unit' =
			
			DIVIDE ( [Net Sales], [Units Sold], 0 )
		lineageTag: 74cedb53-7f30-40dc-929a-93609a0a53f8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WIF Profit' =
			
			IF (
			    [WIF Same] = 0,
			    0,
			    IF (
			        ROUNDDOWN ( [WIF Adjusted Net Sales] - [Net Sales], 0 ) < 0,
			        0,
			        ROUNDDOWN ( [WIF Adjusted Net Sales] - [Net Sales], 0 )
			    )
			)
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: b524dc1e-e1ba-4267-91d2-c57ef6ffa1b8

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Profit Difference' =
			
			DIVIDE ( [WIF Adjusted Sales], [Net Sales], 0 ) - 1
		lineageTag: aa35df95-aff7-4d3d-a722-1955ce6aee72

	measure 'WIF Adjusted Sales' =
			
			[WIF Units Returned_1] * [WIF Price per Unit]
		lineageTag: a0a4e80c-7645-44df-88d3-be04f39594dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'WIF Sales' =
			
			CALCULATE ( [Net Sales], ALL ( 'Calendar'[Date].[Month] ) )
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: 9aea99a5-0f7a-421f-847b-e81ae3188e19

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'WIF Same' =
			
			IF (
			    [% Return Rate Value]
			        >= CALCULATE ( [Return Rate], ALL ( Store[Type] ), ALL ( Store[Store] ) ),
			    0,
			    1
			)
		formatString: 0
		lineageTag: 5fe6697f-11ee-4ae5-92b2-6bed10f4326e

	measure 'WIF Forecast' =
			
			[Net Sales] + [WIF Profit]
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: a19bf6bc-3767-4b5f-b56d-9a6658a817af

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'WIF Total Forecast' =
			
			CALCULATE ( [WIF Forecast], ALL ( 'Calendar'[Date].[Month] ) )
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: 6706b1b0-20a7-43a0-b08c-f6df7eba75ea

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'WIF Total Profit' =
			
			CALCULATE ( [WIF Profit], ALL ( 'Calendar'[Date].[Month] ) )
		formatString: \$#,0;-\$#,0;\$#,0
		lineageTag: 1bed2507-7783-49f6-9a2a-61eb07a646ab

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'WIF Profit Difference' =
			
			DIVIDE ( [WIF Forecast], [Net Sales], 0 ) - 1
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 99a97246-6fb3-4d03-b0d9-7814afa5562d

	measure 'Total Return Rate' =
			
			CALCULATE ( [Return Rate], ALL ( 'Calendar'[Date].[Month] ) )
		formatString: 0%;-0%;0%
		lineageTag: ee417d6a-8fd1-4caf-a61b-fc8b79f72aa0

	measure '_SVG KPI AP' = ```
			
			VAR CardName = "Returns"
			VAR Currents =
			    IF ( [Returns] = 0 || ISBLANK ( [Returns] ), 0, [Returns] )
			VAR Previous =
			    IF ( [Returns PM] = 0 || ISBLANK ( [Returns PM] ), 0, [Returns PM] )
			VAR _Variance = [Returns Variance]
			VAR _VariancePer = [Returns Variance %]
			VAR _ConditionForAll =
			    SWITCH ( TRUE (), _Variance < 0, 1, _Variance > 0, 0, BLANK () )
			VAR _CondArrow =
			    SWITCH ( TRUE (), _Variance < 0, "▼", _Variance > 0, "▲", "-" )
			VAR _Color =
			    SWITCH (
			        TRUE (),
			        _Variance < 0, "#FC1F1F",
			        _Variance > 0, "#00B112",
			        "#DE5B12"
			    )
			VAR _Per_Difference_ =
			    IF ( _VariancePer = 0 || ISBLANK ( _VariancePer ), 0, _VariancePer )
			RETURN
			    "data:image/svg+xml;utf8," & "
			<svg width='300' height='150' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' >
			    <!-- Define a filter for the drop shadow -->
			    <defs>
			        <filter id='drop-shadow' x='-20%' y='-20%' width='140%' height='140%'>
			            <feDropShadow dx='5' dy='5' stdDeviation='5' flood-color='#000000' />
			        </filter>
			    </defs>
			
			    <!-- Draw the white box with the drop shadow filter applied -->
			    <rect x='20' y='20' rx='10' ry='10' width='250' height='107' style='fill: #004369;'/>
			 
			    <text x='71' y='41.5' font-family='Segoe UI' font-size='20' fill='#BDCAEF' text-anchor='left' dominant-baseline='middle' font-weight='bold' >
			    " & CardName & "</text>
			
				<text font-family='Segoe UI' font-size='20' fill='#7C95DE' text-anchor='left' dominant-baseline='middle' font-weight='bold'>
			     <tspan x='28' y='77'  > "
			        & FORMAT ( Currents, "$###,###,##0" ) & " </tspan>
			    <tspan y='70' font-size='13' fill='" & _Color & "'> " & _CondArrow & " "
			        & FORMAT ( _Per_Difference_, "0.0%" ) & " </tspan></text>
			
			  <text x='28' y='105' font-family='Segoe UI' font-size='12' fill='#7C95DE' text-anchor='left' dominant-baseline='middle' font-weight='bold'>
			    <tspan fill='#B3B3B3'> by </tspan>
			    <tspan fill='" & _Color & "'> "
			        & FORMAT ( _Variance, "$###,###,##0" ) & " </tspan>
				<tspan fill='#B3B3B3'>from LM</tspan>
			  </text>
			    <rect x='175' y='52' rx='7' ry='7' width='70' height='50' style='fill: #00395970' stroke='#ffffff50' stroke-width='0.2'/>
				<image x='27' y='27' width='35' height='25' xlink:href='" & [_KPI Icon] & "' />
			
			
			   <image x='233' y='26' width='35' height='25' xlink:href='" & [_KPI Indicators] & "' >
			   <animate attributeName='opacity' values='0;1;0' keyTimes='0;0.5;1' dur='4s' fill='freeze' repeatCount='indefinite' ease='ease-in-out' />
			   </image>
			</svg>
			"
			```
		lineageTag: 9a2f6ec9-c321-473f-abfc-fe7152990df1
		dataCategory: ImageUrl

	measure '_KPI Indicators' =
			
			SWITCH (
			    TRUE (),
			    [Returns Variance] > 0,
			        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFsAAABbCAYAAAAcNvmZAAAACXBIWXMAAAsTAAAL",
			    [Returns Variance] = 0,
			        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFsAAABbCAYAAAAcNvmZAAAACXBIWXMAAAsTAAAL",
			    [Returns Variance] < 0,
			        "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFsAAABbCAYAAAAcNvmZAAAACXBIWXMAAAsTAAAL",
			    BLANK ()
			)
		lineageTag: bbfc6b24-c23d-4f62-8bf7-c28cc061f0c8
		dataCategory: ImageUrl

	measure '_KPI Icon' =
			
			"
			data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHQAAAB7CAYAAAClzKTyAAAACXBIWXMAAAsTAAAL
			"
		lineageTag: 8ff682e4-a231-44d0-893e-adff96206b0c

	measure 'New version KPI 2' = ```
			
			VAR CardName = "Returns"
			VAR Currents =
			    IF ( [Returns] = 0 || ISBLANK ( [Returns] ), 0, [Returns] )
			VAR Previous =
			    IF ( [Returns PM] = 0 || ISBLANK ( [Returns PM] ), 0, [Returns PM] )
			VAR _Variance = [Returns Variance]
			VAR _VariancePer = [Returns Variance %]
			VAR _ConditionForAll =
			    SWITCH ( TRUE (), _Variance < 0, 1, _Variance > 0, 0, BLANK () )
			VAR _CondArrow =
			    SWITCH ( TRUE (), _Variance < 0, "▼", _Variance > 0, "▲", "-" )
			VAR _Color =
			    SWITCH (
			        TRUE (),
			        _Variance < 0, "#FC1F1F",
			        _Variance > 0, "#00B112",
			        "#DE5B12"
			    )
			VAR _Per_Difference_ =
			    IF ( _VariancePer = 0 || ISBLANK ( _VariancePer ), 0, _VariancePer ) // "Date" field used in this example along the X axis
			VAR XMinDate =
			    MIN ( Sales[Date] )
			VAR XMaxDate =
			    MAX ( Sales[Date] ) // Obtain overall min and overall max measure values when evaluated for each date
			VAR YMinValue =
			    MINX ( ALL ( Sales[Date] ), CALCULATE ( [Returns] ) + 0 )
			VAR YMaxValue =
			    MAXX ( ALL ( Sales[Date] ), CALCULATE ( [Returns] ) + 0 ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
			VAR SparklineTable =
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Sales', Sales[Date] ),
			        "X",
			            INT ( 60 * DIVIDE ( Sales[Date] - XMinDate, XMaxDate - XMinDate ) ) + 180,
			        "Y",
			            INT ( 37 * DIVIDE ( [Returns] - YMinValue, YMaxValue - YMinValue ) ) - 45
			    ) // Concatenate X & Y coordinates to build the sparkline
			VAR Lines =
			    CONCATENATEX ( SparklineTable, [X] & "," & 50 - [Y], " ", Sales[Date] )
			RETURN
			    "
			    <svg  xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewbox ='0 0 250 110' '>
			    <defs>
			        <filter id='drop-shadow' x='-20%' y='-20%' width='140%' height='140%'>
			        <feDropShadow dx='5' dy='5' stdDeviation='5' flood-color='#000000' />
			        </filter>
			    </defs>
			
			    <!-- Draw the white box with the drop shadow filter applied -->
			    <rect x='0' y='0' rx='10' ry='10' width='250' height='110' style='fill: #ffffff;'/>
			 
			    <text x='40' y='20.5' font-family='Segoe UI' font-size='20' fill='#4176EB' text-anchor='left' dominant-baseline='middle' font-weight='bold' >
			    " & CardName & "</text>
			    <text font-family='Segoe UI' font-size='20' fill='#7C95DE' text-anchor='left' dominant-baseline='middle' font-weight='bold'>
			     <tspan x='10' y='60'  > "
			        & FORMAT ( Currents, "$##,##0" ) & " </tspan>
			    <tspan y='50' font-size='13' fill='" & _Color & "'> " & _CondArrow & " "
			        & FORMAT ( _Per_Difference_, "0.0%" ) & " </tspan></text>
			
			    <text x='10' y='90' font-family='Segoe UI' font-size='12' fill='#7C95DE' text-anchor='left' dominant-baseline='middle' font-weight='bold'>
			        <tspan fill='#B3B3B3'> by </tspan>
			        <tspan fill='" & _Color & "'> "
			            & FORMAT ( _Variance, "$##,##0" ) & " </tspan>
				    <tspan fill='#B3B3B3'>from LM</tspan>
			    </text>
			
			    <rect x='175' y='52' rx='7' ry='7' width='70' height='50' style='fill: #C6D8FF' stroke='#ffffff50' stroke-width='0.2'/>
			    <defs>
			    <linearGradient id='grad' x1='0' y1='40' x2='0' y2='50' gradientUnits='userSpaceOnUse'>
			        <stop stop-color='steelblue' offset='0' />
			        <stop stop-color='red' offset='1' />
			    </linearGradient>
			    </defs>
			    <polyline fill='none' stroke='#5B7BD6' stroke-width='1' points='" & Lines & "'/>
			
			    
				<image x='2' y='9' width='35' height='25' xlink:href='" & [_KPI Icon] & "' />
			
			
			   <image x='215' y='4' width='35' height='25' xlink:href='" & [_KPI Indicators] & "' >
			   <animate attributeName='opacity' values='0;1;0' keyTimes='0;0.5;1' dur='4s' fill='freeze' repeatCount='indefinite' ease='ease-in-out' />
			   </image>
			
			</svg>
			"
			```
		lineageTag: 55800ca3-fcd6-4421-9a98-b4ecd6e079cd

	measure 'Sparkline Points' = ```
			
			// Static line color - use %23 instead of # for Firefox compatibility (Measure Derived from Eldersveld Modified by Kolosko)
			VAR LineColour = "%23118DFF"
			VAR PointColour = "white" // "Date" field used in this example along the X axis
			VAR XMinDate =
			    MIN ( Sales[Date] )
			VAR XMaxDate =
			    MAX ( Sales[Date] ) // Obtain overall min and overall max measure values when evaluated for each date
			VAR YMinValue =
			    MINX ( VALUES ( Sales[Date] ), CALCULATE ( [Returns] ) )
			VAR YMaxValue =
			    MAXX ( VALUES ( Sales[Date] ), CALCULATE ( [Returns] ) ) // Build table of X & Y coordinates and fit to 50 x 150 viewbox
			VAR SparklineTable =
			    ADDCOLUMNS (
			        SUMMARIZE ( 'Sales', Sales[Date] ),
			        "X",
			            INT ( 150 * DIVIDE ( Sales[Date] - XMinDate, XMaxDate - XMinDate ) ),
			        "Y",
			            INT ( 50 * DIVIDE ( [Returns] - YMinValue, YMaxValue - YMinValue ) )
			    ) // Concatenate X & Y coordinates to build the sparkline
			VAR Lines =
			    CONCATENATEX ( SparklineTable, [X] & "," & 50 - [Y], " ", Sales[Date] )
			VAR PointTable =
			    ADDCOLUMNS (
			        SUMMARIZE ( Sales, Sales[Date] ),
			        "@Colour",
			            IF (
			                [Returns] = YMaxValue,
			                "Green",
			                IF ( [Returns] = YMinValue, "Red", LineColour )
			            ),
			        "@Points",
			            "<circle cx='"
			                & INT ( 150 * DIVIDE ( Sales[Date] - XMinDate, XMaxDate - XMinDate ) ) & "' cy='"
			                & 50
			                    - INT ( 50 * DIVIDE ( [Returns] - YMinValue, YMaxValue - YMinValue ) ) & "' r='3' stroke='" & LineColour & "' stroke-width='1'  fill='" & LineColour & "'/>"
			    ) // Last data points on the line
			VAR LastSparkYValue =
			    MAXX ( FILTER ( SparklineTable, Sales[Date] = XMaxDate ), [Y] )
			VAR LastSparkXValue =
			    MAXX ( FILTER ( SparklineTable, Sales[Date] = XMaxDate ), [X] ) // Add to SVG, and verify Data Category is set to Image URL for this measure
			VAR SVGImageURL =
			    "data:image/svg+xml;utf8," & --- gradient---
			    "<svg xmlns='http://www.w3.org/2000/svg' x='0px' y='0px' viewBox='-7 -7 164 64'>" & --- Lines---
			    "<polyline 
			        fill='transparent' stroke='" & LineColour & "' 
			        stroke-linecap='round' stroke-linejoin='round' 
			        stroke-width='2' points=' " & Lines & " '/>"
			        & --- Last Point---
			        CONCATENATEX ( PointTable, [@Points] ) & "<circle cx='" & LastSparkXValue & "' cy='" & 50 - LastSparkYValue & "' r='4' stroke='" & LineColour & "' stroke-width='3' fill='" & PointColour & "' />" & "</svg>"
			RETURN
			    SVGImageURL
			```
		lineageTag: 78c6f810-0365-4e52-b94b-0df2e41b70de

	measure '_SVG KPI AP _var' =
			
			VAR Currents =
			    IF ( [Returns] = 0 || ISBLANK ( [Returns] ), 0, [Returns] )
			VAR Previous =
			    IF ( [Returns PM] = 0 || ISBLANK ( [Returns PM] ), 0, [Returns PM] )
			VAR _Variance = [Returns Variance]
			VAR _VariancePer = [Returns Variance %]
			VAR _ConditionForAll =
			    SWITCH ( TRUE (), _Variance < 0, 1, _Variance > 0, 0, BLANK () )
			VAR _CondArrow =
			    SWITCH ( TRUE (), _Variance < 0, "▼", _Variance > 0, "▲", "-" )
			VAR _Color =
			    SWITCH (
			        TRUE (),
			        _Variance < 0, "#FC1F1F",
			        _Variance > 0, "#00B112",
			        "#DE5B12"
			    )
			VAR _Per_Difference_ =
			    IF ( _VariancePer = 0 || ISBLANK ( _VariancePer ), 0, _VariancePer )
			RETURN
			    _Variance
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: bf9e5bb3-efc7-4fc6-be0a-8eb0ae1a1296

	measure '_SVG KPI AP _var %' =
			
			VAR Currents =
			    IF ( [Returns] = 0 || ISBLANK ( [Returns] ), 0, [Returns] )
			VAR Previous =
			    IF ( [Returns PM] = 0 || ISBLANK ( [Returns PM] ), 0, [Returns PM] )
			VAR _Variance = [Returns Variance]
			VAR _VariancePer = [Returns Variance %]
			VAR _ConditionForAll =
			    SWITCH ( TRUE (), _Variance < 0, 1, _Variance > 0, 0, BLANK () )
			VAR _CondArrow =
			    SWITCH ( TRUE (), _Variance < 0, "▼", _Variance > 0, "▲", "-" )
			VAR _Color =
			    SWITCH (
			        TRUE (),
			        _Variance < 0, "#FC1F1F",
			        _Variance > 0, "#00B112",
			        "#DE5B12"
			    )
			VAR _Per_Difference_ =
			    IF ( _VariancePer = 0 || ISBLANK ( _VariancePer ), 0, _VariancePer )
			RETURN
			    _CondArrow & FORMAT ( _VariancePer, "0%" )
		lineageTag: f52eeba0-722a-4efe-b5ac-267f129e05c7

	measure '_SVG KPI AP _var color' =
			
			VAR Currents =
			    IF ( [Returns] = 0 || ISBLANK ( [Returns] ), 0, [Returns] )
			VAR Previous =
			    IF ( [Returns PM] = 0 || ISBLANK ( [Returns PM] ), 0, [Returns PM] )
			VAR _Variance = [Returns Variance]
			VAR _VariancePer = [Returns Variance %]
			VAR _ConditionForAll =
			    SWITCH ( TRUE (), _Variance < 0, 1, _Variance > 0, 0, BLANK () )
			VAR _CondArrow =
			    SWITCH ( TRUE (), _Variance < 0, "▼", _Variance > 0, "▲", "-" )
			VAR _Color =
			    SWITCH (
			        TRUE (),
			        _Variance < 0, "#FC1F1F",
			        _Variance > 0, "#00B112",
			        "#DE5B12"
			    )
			VAR _Per_Difference_ =
			    IF ( _VariancePer = 0 || ISBLANK ( _VariancePer ), 0, _VariancePer )
			RETURN
			    _Color
		lineageTag: da6b6b60-894b-4cc8-ac2d-0e33b48d2a41

	measure '_SVG KPI AP Returns' = ```
			
			VAR CardName = "Returns"
			VAR Currents =
			    IF ( [Returns] = 0 || ISBLANK ( [Returns] ), 0, [Returns] )
			VAR Previous =
			    IF ( [Returns PM] = 0 || ISBLANK ( [Returns PM] ), 0, [Returns PM] )
			VAR _Variance = [Returns Variance]
			VAR _VariancePer = [Returns Variance %]
			VAR _ConditionForAll =
			    SWITCH ( TRUE (), _Variance < 0, 1, _Variance > 0, 0, BLANK () )
			VAR _CondArrow =
			    SWITCH ( TRUE (), _Variance < 0, "▼", _Variance > 0, "▲", "-" )
			VAR _Color =
			    SWITCH (
			        TRUE (),
			        _Variance < 0, "#FC1F1F",
			        _Variance > 0, "#00B112",
			        "#DE5B12"
			    )
			VAR _Per_Difference_ =
			    IF ( _VariancePer = 0 || ISBLANK ( _VariancePer ), 0, _VariancePer )
			RETURN
			    "data:image/svg+xml;utf8," & "
			<svg width='300' height='150' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' >
			    <!-- Define a filter for the drop shadow -->
			    <defs>
			        <filter id='drop-shadow' x='-20%' y='-20%' width='140%' height='140%'>
			            <feDropShadow dx='5' dy='5' stdDeviation='5' flood-color='#000000' />
			        </filter>
			    </defs>
			
			    <!-- Draw the white box with the drop shadow filter applied -->
			    <rect x='20' y='20' rx='10' ry='10' width='250' height='107' style='fill: #004369;'/>
			 
			    <text x='71' y='41.5' font-family='Segoe UI' font-size='20' fill='#BDCAEF' text-anchor='left' dominant-baseline='middle' font-weight='bold' >
			    " & CardName & "</text>
			
				<text font-family='Segoe UI' font-size='20' fill='#7C95DE' text-anchor='left' dominant-baseline='middle' font-weight='bold'>
			     <tspan x='28' y='77'  > "
			        & FORMAT ( Currents, "$###,###,##0" ) & " </tspan>
			    <tspan y='70' font-size='13' fill='" & _Color & "'> " & _CondArrow & " "
			        & FORMAT ( _Per_Difference_, "0.0%" ) & " </tspan></text>
			
			  <text x='28' y='105' font-family='Segoe UI' font-size='12' fill='#7C95DE' text-anchor='left' dominant-baseline='middle' font-weight='bold'>
			    <tspan fill='#B3B3B3'> by </tspan>
			    <tspan fill='" & _Color & "'> "
			        & FORMAT ( _Variance, "$###,###,##0" ) & " </tspan>
				<tspan fill='#B3B3B3'>from LM</tspan>
			  </text>
			
				<image x='27' y='27' width='35' height='25' xlink:href='" & [_KPI Icon] & "' />
			
			
			   <image x='233' y='26' width='35' height='25' xlink:href='" & [_KPI Indicators] & "' >
			   <animate attributeName='opacity' values='0;1;0' keyTimes='0;0.5;1' dur='4s' fill='freeze' repeatCount='indefinite' ease='ease-in-out' />
			   </image>
			</svg>
			"
			```
		lineageTag: 07cfe409-7aae-4ca6-9eb2-9edf44b4f8bf

	column Spacer = " "
		lineageTag: 340e19af-496b-4d91-9b19-6413923705f5
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Analysis DAX-974df033-112a-4cf0-a45f-a45006d690ca' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

