table KPI
	lineageTag: ea6ca85c-c508-47ce-922b-c987bacd6d47

	measure Discount = sum(Sales[Discount])
		lineageTag: 5a30e479-bd13-4dd5-b5a0-88f615a6bccb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Column1
		dataType: string
		lineageTag: 5e7963c6-1a5d-4b4c-baec-d3bba0b3786d
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition KPI-8fa56063-affa-494a-96a5-f52736901676 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

